use tauri::{AppHandle, Listener, Manager, WebviewUrl, WebviewWindowBuilder, Emitter};
use std::fs;

/// 获取应用专用的内置 cookies.txt 路径
fn get_internal_cookie_path(app: &AppHandle) -> std::path::PathBuf {
    let app_dir = app.path().app_data_dir().unwrap_or_else(|_| std::path::PathBuf::from("./"));
    app_dir.join("cookies.txt")
}

/// 解析单行 raw cookie 并转换为 Netscape HTTP Cookie File 格式的单行
fn format_cookie_to_netscape(domain: &str, raw_cookie: &str) -> String {
    let mut lines = String::new();
    let parts = raw_cookie.split(';');
    for part in parts {
        let kv = part.trim();
        if kv.is_empty() { continue; }
        
        let mut split = kv.splitn(2, '=');
        let name = split.next().unwrap_or("");
        let value = split.next().unwrap_or("");
        
        if name.is_empty() { continue; }

        let formatted_domain = if domain.starts_with('.') { domain.to_string() } else { format!(".{}", domain) };
        let include_subdomains = "TRUE";
        let path = "/";
        let secure = "FALSE";
        // 赋予一个默认的一年后的过期时间时间戳，防止 yt-dlp 拒绝读取
        let expiry = chrono::Utc::now().timestamp() + 31536000;

        lines.push_str(&format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
            formatted_domain, include_subdomains, path, secure, expiry, name, value
        ));
    }
    lines
}

/// 初始化高级嗅探器逻辑 (基于 Tauri 2 Webview 与猫抓级多层级脚本注入)
pub async fn init_sniffer(url: String, app: AppHandle) -> Result<(), String> {
    let label = "sniffer_window";

    if let Some(win) = app.get_webview_window(label) {
        let _ = win.close();
    }

    // 利用 Rust 宏在编译期将 JS 文件内容硬编码到二进制文件中
    let script_base = include_str!("scripts/adapters/base.js");
    let script_douyin = include_str!("scripts/adapters/douyin.js");
    let script_pikpak = include_str!("scripts/adapters/pikpak.js");
    let script_aliyun = include_str!("scripts/adapters/aliyun.js");
    let script_gdstudio = include_str!("scripts/adapters/gdstudio.js");
    let script_universal = include_str!("scripts/adapters/universal.js");
    let script_core = include_str!("scripts/core.js");

    // 组合注入脚本，必须保证注入顺序：基类 -> 独立适配器 -> 兜底适配器 -> 核心引擎
    let init_script = format!(
        "{}\n{}\n{}\n{}\n{}\n{}\n{}",
        script_base,
        script_douyin,
        script_pikpak,
        script_aliyun,
        script_gdstudio,
        script_universal,
        script_core
    );

    let app_handle_clone = app.clone();
    app.listen("sniffed_cookie", move |event| {
        if let Ok(payload) = serde_json::from_str::<serde_json::Value>(event.payload()) {
            if let (Some(domain), Some(cookie)) = (payload.get("domain").and_then(|d| d.as_str()), payload.get("cookie").and_then(|c| c.as_str())) {
                let cookie_path = get_internal_cookie_path(&app_handle_clone);
                
                let mut content = String::from("# Netscape HTTP Cookie File\n");
                content.push_str("# This file was generated by DL-Omni Internal Sniffer\n\n");
                content.push_str(&format_cookie_to_netscape(domain, cookie));

                let _ = fs::write(&cookie_path, content);
            }
        }
    });

    let win = WebviewWindowBuilder::new(&app, label, WebviewUrl::External(url.parse().unwrap()))
        .title("DL-Omni - 资源嗅探器 (猫抓级多路引擎)")
        .inner_size(1100.0, 800.0)
        .initialization_script(&init_script)
        .build()
        .map_err(|e| format!("无法创建嗅探窗口: {}", e))?;

    let app_clone = app.clone();
    win.on_window_event(move |event| {
        if let tauri::WindowEvent::Destroyed = event {
            let _ = app_clone.emit("sniffer_window_closed", ());
        }
    });

    Ok(())
}

pub async fn stop_sniffer(app: AppHandle) -> Result<(), String> {
    if let Some(win) = app.get_webview_window("sniffer_window") {
        win.close().map_err(|e| format!("关闭嗅探窗口失败: {}", e))?;
    }
    Ok(())
}